### ISSUE TITLE
Question on Generating Locus-Level Embeddings

### ISSUE THREAD

**Issue by muyuyang** [Noble-Lab/HiCFoundation#1]
Thank you for sharing this fantastic work!

I have a question about the generation of embeddings. In the paper, it is mentioned that HiCFoundation is capable of generating embeddings for a single genomic locus. However, the instructions provided for "Generate multi-scale Hi-C embeddings" only describe how to generate patch, submatrix, chromosome, and genome-wide embeddings.

Could you please clarify how I can generate locus-level embeddings using HiCFoundation? Thank you so much!

**Comment by wang3702** [comment]
Thank you so much for your interest in our work!

For locus embedding, you can specify a submatrix with a shape of 16*4000 and scan along the diagonal line, then you can use this submatrix embedding as the center locus embedding.

**Comment by muyuyang** [comment]
Thank you so much for your prompt response! It's very helpful. I'll explore the locus embeddings based on your suggestions.
